services:
  bot:
    container_name: bot
    build: ./bot
    environment:
      HOST: ${RM_HOST}
      PORT: ${RM_PORT}
      USER: ${RM_USER}
      PASSWORD: ${RM_PASSWORD}
      TOKEN: ${TOKEN}
      DBHOST: ${DB_HOST}
      DBPORT: ${DB_PORT}
      DBUSER: ${DB_USER}
      DBPASSWORD: ${DB_PASSWORD}
      DBNAME: ${DB_DATABASE}
    env_file:
      - .env
    volumes:
      - pg_logs:/var/log/
    networks:
      - botnet
  db:
    container_name: db
    build:
      context: ./db
      args:
        DB_REPL_USER: ${DB_REPL_USER}
        DB_REPL_PASSWORD: ${DB_REPL_PASSWORD}
        DB_DATABASE: ${DB_DATABASE}
        DB_PORT: ${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    env_file:
      - .env
    volumes:
      - pg_logs:/var/log/
    networks:
      - botnet
  db_repl:
    container_name: db_repl
    build:
      context: ./db_repl
      args:
        DB_REPL_HOST: ${DB_REPL_HOST}
        DB_REPL_PORT: ${DB_REPL_PORT}
        DB_REPL_USER: ${DB_REPL_USER}
        DB_REPL_PASSWORD: ${DB_REPL_PASSWORD}
        DB_PORT: ${DB_PORT}
        DB_HOST: ${DB_HOST}
        DB_DATABASE: ${DB_DATABASE}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGUSER: ${DB_REPL_USER}
      PGPASSWORD: ${DB_REPL_PASSWORD}
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - botnet
      
volumes:
  pg_logs:  

networks:
  botnet:
    driver: bridge
